[build]
buildCommand = "npm run server:build && npx drizzle-kit push && node scripts/build.js"

[deploy]
startCommand = "npm run server:prod"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
