const { withGradleProperties } = require("@expo/config-plugins");

// Give Gradle enough Metaspace to lint React Native.
//
// Expo's default gradle.properties ships:
//   org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
//
// Android lint loads every Kotlin source it analyses into Metaspace, and
// React Native's own sources blow past 512m. It doesn't fail as a lint
// warning — the whole build dies:
//
//   Unexpected failure during lint analysis of ReactContext.kt
//     (this is a bug in lint or one of the libraries it depends on)
//   Message: Metaspace
//   Stack: OutOfMemoryError
//
// lintVitalRelease runs on every release build, so this takes out `assembleRelease`
// and `bundleRelease` alike — locally and on EAS. Skipping lint hides it but
// gives up the release-blocking checks lintVital exists to run, so raise the
// ceiling instead.
//
// This has to be a config plugin rather than an edit to android/gradle.properties:
// that file is regenerated by every prebuild, and EAS prebuilds from a clean
// checkout, so a hand-edit would silently vanish exactly when it matters.
//
// 4g heap / 2g Metaspace fits comfortably on a 16 GB machine and on EAS's
// Linux builders.
const JVM_ARGS = "-Xmx4096m -XX:MaxMetaspaceSize=2048m";

module.exports = function withGradleMemory(config) {
  return withGradleProperties(config, (config) => {
    const existing = config.modResults.find(
      (item) => item.type === "property" && item.key === "org.gradle.jvmargs"
    );

    if (existing) {
      existing.value = JVM_ARGS;
    } else {
      config.modResults.push({
        type: "property",
        key: "org.gradle.jvmargs",
        value: JVM_ARGS,
      });
    }

    return config;
  });
};
