// YTC: rebbeim + alumni directory. Verbatim port from
// /tmp/ytc-source/expo-app/app/(tabs)/contacts.tsx with imports remapped.
import React, { useCallback, useDeferredValue, useEffect, useMemo, useState } from "react";
import {
  View, Text, SectionList, StyleSheet, TouchableOpacity, TextInput,
  ActivityIndicator, Platform, RefreshControl, StatusBar,
} from "react-native";
import { Image } from "expo-image";
import { SafeAreaView, useSafeAreaInsets } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { ytcColors as Colors } from "@/constants/ytcColors";
import { fetchRebbeim, fetchApprovedAlumni, fetchMyAlumniContact, invalidateYtcCache } from "@/lib/ytc/firebase";
import { useYtcAuth } from "@/contexts/YtcAuthContext";
import { SubmitAlumniContactModal } from "@/components/ytc/SubmitAlumniContactModal";
import { copyToClipboard } from "@/lib/ytc/copy";
import { resizedImageUrl, IMG_THUMB } from "@/lib/image-resize";
import type { Rebbe, AlumniContact } from "@/types/ytc";

type ContactTab = "rebbeim" | "alumni";

export default function ContactsScreen() {
  const insets = useSafeAreaInsets();
  const { user } = useYtcAuth();
  const [rebbeim, setRebbeim] = useState<Rebbe[]>([]);
  const [alumni, setAlumni] = useState<AlumniContact[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [activeTab, setActiveTab] = useState<ContactTab>("rebbeim");
  const [alumniSearch, setAlumniSearch] = useState("");
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [alumniPage, setAlumniPage] = useState(1);
  const [showSubmit, setShowSubmit] = useState(false);
  const ALUMNI_PAGE_SIZE = 50;

  // The signed-in user's own alumni-directory doc.
  //
  // Source of truth: scan `alumniContactSubmissions` for any doc whose
  // `email` field matches user.email — same lookup the website uses
  // (verified against /tmp/ytc-website/app/contacts/contacts-content.tsx).
  // The doc IDs in this collection are auto-generated by the website's
  // addDoc() so a doc-ID lookup keyed by lowercased-email would miss
  // every record created via the website (which is most of them) —
  // that was the actual root cause of "still says add yourself."
  //
  // The mobile-side submission flow now also uses addDoc/setDoc-by-existing-id
  // (see firebase.ts → submitAlumniContact) so there's only ever one
  // doc per user across surfaces.
  // Tri-state: null = haven't loaded yet, false = no doc, true = has a doc.
  const [hasMyEntry, setHasMyEntry] = useState<boolean | null>(null);
  // The merged list still gets a "You" badge + inline edit on the
  // user's own row when they show up in the approved list. Match by
  // raw email (case-sensitive, mirroring website).
  const myAlumniEntry = user?.email ? alumni.find((a) => a.email === user.email) : undefined;

  const loadData = async () => {
    try {
      const [r, a] = await Promise.all([fetchRebbeim(), fetchApprovedAlumni()]);
      setRebbeim(r as Rebbe[]);
      setAlumni(a as AlumniContact[]);
    } catch (e) {
      console.error("YTC Contacts load error:", e);
    } finally {
      setIsLoading(false);
      setRefreshing(false);
    }
  };

  // Independent self-lookup. Runs once when the user's email becomes
  // known and again whenever the directory cache invalidates so a
  // fresh edit promotes the button → "Edit your info" without a
  // forced reload.
  useEffect(() => {
    if (!user?.email) { setHasMyEntry(false); return; }
    // Pass raw email — fetchMyAlumniContact now scans by `email` field.
    fetchMyAlumniContact(user.email)
      .then((entry) => setHasMyEntry(!!entry))
      .catch(() => setHasMyEntry(false));
  }, [user?.email, alumni.length]);

  useEffect(() => { loadData(); }, []);
  const onRefresh = useCallback(async () => {
    setRefreshing(true);
    await Promise.all([invalidateYtcCache("rebbeim"), invalidateYtcCache("approvedAlumni")]);
    loadData();
  }, []);

  // Defer the search input + lowercase the needle once per stable input.
  // Without this the filter scanned 500+ alumni twice per character (.name
  // + .location both lower-cased per row) on every keystroke. With
  // useDeferredValue the typing stays responsive even if the filter pass
  // is slow, and memoizing the needle eliminates 1000+ tiny string allocs.
  const deferredAlumniSearch = useDeferredValue(alumniSearch);
  const filteredAlumni = useMemo(() => {
    if (!deferredAlumniSearch) return alumni;
    const needle = deferredAlumniSearch.toLowerCase();
    return alumni.filter(a =>
      a.name.toLowerCase().includes(needle)
      || (a.location?.toLowerCase().includes(needle) ?? false),
    );
  }, [alumni, deferredAlumniSearch]);

  // Reset pagination when search/tab changes so the first results render fast.
  useEffect(() => { setAlumniPage(1); }, [alumniSearch, activeTab]);

  // Slice the visible window. SectionList's onEndReached bumps the page;
  // the user sees an instant first paint with up to 50 contacts and more
  // load on scroll. With ~hundreds of alumni the full-list render was the
  // slowest part of contacts; this paginates without a network round trip.
  const visibleCount = alumniPage * ALUMNI_PAGE_SIZE;
  const visibleAlumni = filteredAlumni.slice(0, visibleCount);
  const hasMoreAlumni = filteredAlumni.length > visibleCount;

  const alumniSections = Object.entries(
    visibleAlumni.reduce<Record<string, AlumniContact[]>>((acc, contact) => {
      const letter = contact.name[0]?.toUpperCase() ?? "#";
      if (!acc[letter]) acc[letter] = [];
      acc[letter].push(contact);
      return acc;
    }, {}),
  )
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([title, data]) => ({ title, data }));

  // openPhone / openEmail removed in favor of copy-to-clipboard
  // (lib/ytc/copy.ts). Tap the row → copies the value + flashes a
  // toast. Mirrors the website's behavior.

  return (
    <SafeAreaView style={styles.safe} edges={[]}>
      <StatusBar barStyle="light-content" backgroundColor={Colors.navy} />
      <View style={[styles.header, { paddingTop: insets.top + 12 }]}>
        <Text style={styles.headerTitle}>Directory</Text>
        <Text style={styles.headerSubtitle}>Connect with Rebbeim and fellow alumni</Text>
      </View>

      <View style={styles.tabRow}>
        {(["rebbeim", "alumni"] as ContactTab[]).map((tab) => (
          <TouchableOpacity key={tab} style={[styles.tab, activeTab === tab && styles.tabActive]} onPress={() => setActiveTab(tab)}>
            <Text style={[styles.tabText, activeTab === tab && styles.tabTextActive]}>{tab === "rebbeim" ? "Rebbeim" : "Alumni"}</Text>
          </TouchableOpacity>
        ))}
      </View>

      {/* Top-of-list button — only when the self-lookup confirms NO
           doc exists. While `hasMyEntry === null` we haven't checked
           yet, so suppress to avoid flashing "Add yourself" at users
           who already have a pending submission. After submitting,
           the user can edit inline from their own card (look for the
           "You" badge), or use "Edit your info" if their submission
           is still pending and not in the approved list yet. */}
      {activeTab === "alumni" && user?.email && hasMyEntry === false && (
        <TouchableOpacity style={styles.editMyInfoBtn} onPress={() => setShowSubmit(true)}>
          <Ionicons name="person-add-outline" size={14} color={Colors.cream} />
          <Text style={styles.editMyInfoText}>Add yourself to the directory</Text>
        </TouchableOpacity>
      )}
      {activeTab === "alumni" && user?.email && hasMyEntry === true && !myAlumniEntry && (
        <TouchableOpacity style={styles.editMyInfoBtn} onPress={() => setShowSubmit(true)}>
          <Ionicons name="create-outline" size={14} color={Colors.cream} />
          <Text style={styles.editMyInfoText}>Edit your info</Text>
        </TouchableOpacity>
      )}

      <SubmitAlumniContactModal
        visible={showSubmit}
        onClose={() => setShowSubmit(false)}
        onSubmitted={() => { invalidateYtcCache("approvedAlumni").then(() => loadData()); }}
        submitterEmail={user?.email ?? ""}
        submitterDisplayName={user?.displayName ?? null}
      />

      {isLoading ? (
        <View style={styles.loader}><ActivityIndicator size="large" color={Colors.navy} /></View>
      ) : activeTab === "rebbeim" ? (
        <SectionList
          sections={[{ title: "", data: rebbeim }]}
          keyExtractor={(item) => item.id}
          refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor={Colors.navy} />}
          contentContainerStyle={styles.listContent}
          renderItem={({ item: rebbe }) => {
            const isExpanded = expandedId === rebbe.id;
            const hasContact = !!(rebbe.email || rebbe.phone);
            return (
              <TouchableOpacity
                style={styles.rebbeCard}
                onPress={() => hasContact && setExpandedId(isExpanded ? null : rebbe.id)}
                activeOpacity={hasContact ? 0.7 : 1}
              >
                <View style={styles.rebbeRow}>
                  {rebbe.photoUrl
                    ? <Image source={{ uri: resizedImageUrl(rebbe.photoUrl, IMG_THUMB)! }} style={styles.rebbePhoto} contentFit="cover" cachePolicy="memory-disk" recyclingKey={rebbe.id} transition={150} />
                    : <View style={styles.rebbePhotoPlaceholder}>
                        <Ionicons name="person-outline" size={28} color={Colors.gold} />
                      </View>}
                  <View style={styles.rebbeInfo}>
                    <Text style={styles.rebbeName}>{rebbe.name}</Text>
                    <Text style={styles.rebbeTitle}>{rebbe.title}</Text>
                  </View>
                  {hasContact && (
                    <Ionicons
                      name={isExpanded ? "chevron-up" : "chevron-down"}
                      size={18}
                      color={Colors.navyOpacity50}
                    />
                  )}
                </View>
                {isExpanded && hasContact && (
                  <View style={styles.rebbeContactBlock}>
                    {rebbe.email && (
                      <TouchableOpacity
                        style={styles.copyRow}
                        onPress={() => copyToClipboard(rebbe.email!, "Email")}
                      >
                        <Ionicons name="mail-outline" size={16} color={Colors.navy} />
                        <Text style={styles.copyValue} numberOfLines={1}>{rebbe.email}</Text>
                        <Ionicons name="copy-outline" size={16} color={Colors.gold} />
                      </TouchableOpacity>
                    )}
                    {rebbe.phone && (
                      <TouchableOpacity
                        style={styles.copyRow}
                        onPress={() => copyToClipboard(rebbe.phone!, "Phone")}
                      >
                        <Ionicons name="call-outline" size={16} color={Colors.navy} />
                        <Text style={styles.copyValue} numberOfLines={1}>{rebbe.phone}</Text>
                        <Ionicons name="copy-outline" size={16} color={Colors.gold} />
                      </TouchableOpacity>
                    )}
                  </View>
                )}
              </TouchableOpacity>
            );
          }}
          ListEmptyComponent={<EmptyState message="No rebbeim found" />}
          renderSectionHeader={() => null}
        />
      ) : (
        <>
          <View style={styles.searchRow}>
            <View style={styles.searchBox}>
              <Ionicons name="search" size={16} color={Colors.navyOpacity50} style={{ marginRight: 8 }} />
              <TextInput style={styles.searchInput} placeholder="Search alumni..." placeholderTextColor={Colors.navyOpacity50} value={alumniSearch} onChangeText={setAlumniSearch} />
              {alumniSearch ? <TouchableOpacity onPress={() => setAlumniSearch("")}><Ionicons name="close-circle" size={18} color={Colors.navyOpacity50} /></TouchableOpacity> : null}
            </View>
          </View>
          <SectionList
            sections={alumniSections}
            keyExtractor={(item) => item.id}
            refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor={Colors.navy} />}
            contentContainerStyle={styles.listContent}
            stickySectionHeadersEnabled
            renderSectionHeader={({ section }) => (
              <View style={styles.sectionHeader}><Text style={styles.sectionHeaderText}>{section.title}</Text></View>
            )}
            renderItem={({ item: contact }) => {
              const isExpanded = expandedId === contact.id;
              // Match by email field (mirrors website). Doc IDs are
              // auto-generated and don't correlate to the user's email.
              const isMine = !!user?.email && contact.email === user.email;
              return (
                <TouchableOpacity style={[styles.alumniCard, isMine && styles.alumniCardMine]} onPress={() => setExpandedId(isExpanded ? null : contact.id)}>
                  <View style={styles.alumniRow}>
                    <View style={[styles.alumniAvatar, isMine && styles.alumniAvatarMine]}><Text style={styles.alumniAvatarText}>{contact.name[0]}</Text></View>
                    <View style={styles.alumniInfo}>
                      <View style={styles.alumniNameRow}>
                        <Text style={styles.alumniName}>{contact.name}</Text>
                        {isMine && <View style={styles.youBadge}><Text style={styles.youBadgeText}>You</Text></View>}
                      </View>
                      {contact.location && <Text style={styles.alumniLocation}>{contact.location}</Text>}
                    </View>
                    <Ionicons name={isExpanded ? "chevron-up" : "chevron-down"} size={16} color={Colors.navyOpacity50} />
                  </View>
                  {isExpanded && (
                    <View style={styles.alumniExpanded}>
                      {contact.email && (
                        <TouchableOpacity
                          style={styles.copyRow}
                          onPress={() => copyToClipboard(contact.email!, "Email")}
                        >
                          <Ionicons name="mail-outline" size={16} color={Colors.navy} />
                          <Text style={styles.copyValue} numberOfLines={1}>{contact.email}</Text>
                          <Ionicons name="copy-outline" size={16} color={Colors.gold} />
                        </TouchableOpacity>
                      )}
                      {contact.phone && (
                        <TouchableOpacity
                          style={styles.copyRow}
                          onPress={() => copyToClipboard(contact.phone!, "Phone")}
                        >
                          <Ionicons name="call-outline" size={16} color={Colors.navy} />
                          <Text style={styles.copyValue} numberOfLines={1}>{contact.phone}</Text>
                          <Ionicons name="copy-outline" size={16} color={Colors.gold} />
                        </TouchableOpacity>
                      )}
                      {isMine && (
                        <TouchableOpacity style={styles.editMyInline} onPress={() => setShowSubmit(true)}>
                          <Ionicons name="create-outline" size={16} color={Colors.cream} />
                          <Text style={styles.editMyInlineText}>Edit your info</Text>
                        </TouchableOpacity>
                      )}
                    </View>
                  )}
                </TouchableOpacity>
              );
            }}
            ListEmptyComponent={<EmptyState message="No alumni found" />}
            onEndReachedThreshold={0.5}
            onEndReached={() => { if (hasMoreAlumni) setAlumniPage((p) => p + 1); }}
            ListFooterComponent={hasMoreAlumni ? (
              <View style={styles.loadMoreFooter}>
                <ActivityIndicator size="small" color={Colors.navy} />
                <Text style={styles.loadMoreText}>Loading more…</Text>
              </View>
            ) : null}
          />
        </>
      )}
    </SafeAreaView>
  );
}

function EmptyState({ message }: { message: string }) {
  return (
    <View style={styles.empty}>
      <Ionicons name="person-outline" size={40} color={Colors.navyOpacity30} />
      <Text style={styles.emptyText}>{message}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.cream },
  header: { backgroundColor: Colors.navy, paddingTop: 8, paddingBottom: 10, alignItems: "center" },
  headerTitle: { color: Colors.cream, fontSize: 18, fontWeight: "bold", fontFamily: Platform.OS === "ios" ? "Georgia" : "serif" },
  headerSubtitle: { color: Colors.creamOpacity70, fontSize: 12, marginTop: 2 },
  // Tab selector — slimmed per user feedback (was 10px vertical pad +
  // 6px outer pad, now 6px + 4px). Same shape, less screen weight.
  tabRow: { flexDirection: "row", backgroundColor: Colors.white, padding: 4, marginHorizontal: 12, marginTop: 8, marginBottom: 8, borderRadius: 10, shadowColor: Colors.black, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 3, elevation: 1 },
  tab: { flex: 1, paddingVertical: 6, alignItems: "center", borderRadius: 6 },
  tabActive: { backgroundColor: Colors.navy },
  tabText: { fontSize: 13, fontWeight: "500", color: Colors.navyOpacity70 },
  tabTextActive: { color: Colors.cream },
  loader: { flex: 1, justifyContent: "center", alignItems: "center" },
  listContent: { padding: 12, paddingBottom: 120 },
  searchRow: { paddingHorizontal: 12, paddingBottom: 8 },
  searchBox: { flexDirection: "row", alignItems: "center", backgroundColor: Colors.white, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 6, borderWidth: 1, borderColor: Colors.creamDark },
  searchInput: { flex: 1, fontSize: 14, color: Colors.navy, paddingVertical: 0 },
  rebbeCard: { backgroundColor: Colors.white, borderRadius: 14, padding: 14, marginBottom: 10, shadowColor: Colors.black, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06, shadowRadius: 6, elevation: 2 },
  rebbeRow: { flexDirection: "row", alignItems: "center", gap: 14 },
  rebbeContactBlock: { marginTop: 10, paddingTop: 10, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: Colors.creamDark, gap: 8 },
  copyRow: {
    flexDirection: "row", alignItems: "center", gap: 10,
    paddingVertical: 8, paddingHorizontal: 10,
    backgroundColor: Colors.cream, borderRadius: 8,
  },
  copyValue: { flex: 1, fontSize: 13, color: Colors.navy },
  rebbePhoto: { width: 64, height: 64, borderRadius: 32, backgroundColor: Colors.creamDark },
  rebbePhotoPlaceholder: { width: 64, height: 64, borderRadius: 32, backgroundColor: Colors.navy, alignItems: "center", justifyContent: "center" },
  rebbeInitial: { color: Colors.gold, fontSize: 24, fontWeight: "bold" },
  rebbeInfo: { flex: 1 },
  rebbeName: { fontSize: 16, fontWeight: "600", color: Colors.navy },
  rebbeTitle: { fontSize: 13, color: Colors.navyOpacity70, marginTop: 2 },
  contactBtns: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 8 },
  contactBtn: { flexDirection: "row", alignItems: "center", gap: 4, paddingHorizontal: 12, paddingVertical: 6, backgroundColor: Colors.goldOpacity15, borderRadius: 20 },
  contactBtnText: { fontSize: 12, color: Colors.navy, fontWeight: "500" },
  sectionHeader: { backgroundColor: Colors.creamDark, paddingHorizontal: 16, paddingVertical: 6 },
  sectionHeaderText: { fontSize: 13, fontWeight: "700", color: Colors.navyOpacity50, letterSpacing: 0.5 },
  alumniCard: { backgroundColor: Colors.white, borderRadius: 12, marginBottom: 6, overflow: "hidden", shadowColor: Colors.black, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 3, elevation: 1 },
  alumniCardMine: { borderWidth: 1, borderColor: Colors.gold },
  alumniRow: { flexDirection: "row", alignItems: "center", padding: 14, gap: 12 },
  alumniAvatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: Colors.navyOpacity10, alignItems: "center", justifyContent: "center" },
  alumniAvatarMine: { backgroundColor: Colors.goldOpacity15 },
  alumniAvatarText: { fontSize: 16, fontWeight: "600", color: Colors.navy },
  alumniInfo: { flex: 1 },
  alumniNameRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  alumniName: { fontSize: 15, fontWeight: "500", color: Colors.navy },
  youBadge: { backgroundColor: Colors.gold, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 10 },
  youBadgeText: { fontSize: 10, color: Colors.navy, fontWeight: "700", letterSpacing: 0.4 },
  alumniLocation: { fontSize: 12, color: Colors.navyOpacity50, marginTop: 2 },
  alumniExpanded: { paddingHorizontal: 14, paddingBottom: 14 },
  editMyInline: {
    flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6,
    backgroundColor: Colors.navy, marginTop: 10,
    paddingVertical: 10, borderRadius: 10,
  },
  editMyInlineText: { color: Colors.cream, fontSize: 13, fontWeight: "500" },
  empty: { alignItems: "center", padding: 40, gap: 12 },
  emptyText: { fontSize: 15, color: Colors.navyOpacity50 },
  loadMoreFooter: { flexDirection: "row", alignItems: "center", justifyContent: "center", padding: 16, gap: 8 },
  loadMoreText: { fontSize: 13, color: Colors.navyOpacity70 },
  // "Add yourself" / "Edit your info" CTA — slimmed (was 10pv).
  editMyInfoBtn: {
    flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6,
    backgroundColor: Colors.navy, marginHorizontal: 12, marginBottom: 6,
    paddingVertical: 7, borderRadius: 8,
  },
  editMyInfoText: { color: Colors.cream, fontSize: 12, fontWeight: "500" },
});
